export const data = {
    "sites": [
        {
        "name": "Timeless Blue Nights",
        "temperature": -4,
        "vegetation": "none",
        "inhabitants": 0,
        "animals": "no animal species",
        "description": "No matter what time you come here, there are eternal dark blue nights. It's a beautiful place to enjoy solitude and think. Make sure you wear warm clothes.",
        "img": "./Images/aesthetic-dark-wallpaper-background-neon-light-small.jpg",
        "labels": "solitude, cold, sand, eternal night, dunes, silence",
        "title": "Image made by rawpixel.com",
        "alt": "Timeless Blue Nights",
        "id": 1 
    },
    {
        "name": "Luminescence Forrest",
        "temperature": 22,
        "vegetation": "trees, bushes and flowers",
        "inhabitants": 150,
        "animals": "birds, unicorns and rabbits",
        "description": "Discover flowers, plants and animals in all colors. If you respect nature, the locals will happily guide you to Lake Luminescence and tell you about their lives.",
        "img": "./Images/digital-art-7524165_640.jpg",
        "labels": "lights, forrest, trees, animals, lake, hiking, walking, lake",
        "title": "Image made by gun1215 on pixabay.com",
        "alt": "Luminescence Forrest",
        "id": 2
    },
    {
        "name": "Mount Riverside",
        "temperature": 18,
        "vegetation": "trees, bushes and flowers",
        "inhabitants": 120,
        "animals": "bears, birds and fish",
        "description": "Cross the river on the back of a saddlefish and discover hidden life in the forest. Enjoy a barbecue with the locals, then climb Mount Flake for a magical sky view.",
        "img": "./Images/fantasy-1481184_640.jpg",
        "labels": "mountain, climbing, hiking, river, fish, barbecue, adventure, forrest, animals",
        "title": "Image made by karlfrey on pixabay.com",
        "alt": "Mount Riverside",
        "id": 3
    },
    {
        "name": "Optilusiana",
        "temperature": 20,
        "vegetation": "trees and bushes",
        "inhabitants": 25000,
        "animals": "birds",
        "description": "Which side is really up? Forget everything you know about gravity when you come here and just enjoy the experience. End your visit with a hot air balloon ride.",
        "img": "./Images/fantasy-2543658_640.jpg",
        "labels": "hot air balloon, walking, illusion, magic, upside down, gravity, party, music, museum",
        "title": "Image made by kellepics on pixabay.com",
        "alt": "Optilusiana",
        "id": 4
    },
    {
        "name": "Grotto Dome Park",
        "temperature": 16,
        "vegetation": "trees and bushes",
        "inhabitants": 40,
        "animals": "birds, deer, bears, wolves and fish",
        "description": "Hidden behind a grotto, many people sail by without discovering its serene beauty. Take long walks without encountering a lot of hikers and become one with your surroundings. Leave with a peaceful mind.",
        "img": "./Images/fantasy-2750995_640.jpg",
        "labels": "grotto, park, hiking, walking, swimming, solitude, peace, forrest, animals",
        "title": "Image made by kellepics on pixabay.com",
        "alt": "Grotto Dome Park",
        "id": 5
    },
    {
        "name": "Eerabouts",
        "temperature": 9,
        "vegetation": "trees and bushes",
        "inhabitants": 80,
        "animals": "birds, rabbits, ghostly dogs and horses",
        "img": "./Images/fantasy-2935246_640.jpg",
        "labels": "ghosts, mystery, desolate, creepy, scary, adventure",
        "description": "No need to know if what you saw was really there. It's all about the experience. Explore abandoned mansions. Argue about who moved your bag or that table, while nobody else was there. Probably.",
        "title": "Image made by darksouls1 on pixabay.com",
        "alt": "Eerabouts",
        "id": 6
    },
    {
        "name": "Bright Cascades",
        "temperature": 20,
        "vegetation": "trees and bushes",
        "inhabitants": 12000,
        "animals": "birds, rabbits and wolves",
        "img": "./Images/fantasy-3791009_640.jpg",
        "labels": "library, picturesque, waterfall, music, mansion, history, walking, museum, art",
        "description": "Be greeted by dancing ladies who serve refreshments. The lute and harp music in the background was written centuries ago by long forgotten composers. Watch rare scrolls in Promise Library. Stroll along picturesque buildings over cobbled streets with a view of Promise Waterfalls.",
        "title": "Image made by darksouls1 on pixabay.com",
        "alt": "Bright Cascades",
        "id": 7
    },
    {
        "name": "Mingled Abode",
        "temperature": 30,
        "vegetation": "trees, bushes and flowers",
        "inhabitants": 800,
        "animals": "birds, rabbits, unicorns and bears",
        "description": "In Mingled Abode nature is kept intact when making homes. The way of life does not hurt nor disturb nature. Interact with animals who come to greet you during your hikes.",
        "img": "./Images/fantasy-4388628_640.jpg",
        "labels": "nature, wild life, hiking, walking, animals, adventure",
        "title": "Image made by Willgard on pixabay.com",
        "alt": "Mingled Abode",
        "id": 8
    },
    {
        "name": "Grim Hails",
        "temperature": 10,
        "vegetation": "trees and moss",
        "inhabitants": 28,
        "animals": "birds, wolves and fish",
        "description": "Go on a dangerous and difficult hike. If you survive and reach Desolate Castle, enjoy the glum view as long as you're allowed to rest there. Make sure to bring your own food. Only for those seeking a challenge.",
        "img": "./Images/mountains-7685801_640.jpg",
        "labels": "cliffs, mountain, river, desolation, hiking, climbing, solitude, adventure, challenge, castle, danger",
        "title": "Image made by Alan_Frijns on pixabay.com",
        "alt": "Grim Hails",
        "id": 9
    },
    {
        "name": "Boulder Island",
        "temperature": 7,
        "vegetation": "bushes and moss",
        "inhabitants": 28,
        "animals": "fish and snakes",
        "description": "Learn how to make bread and butter. Eat it with grilled meat and vegetables, prepared after an ancient recipe. Take a tour in Atoll Castle, view the first button ever made and discover the history of Boulder Island.",
        "img": "./Images/mountains-7955060_640.jpg",
        "labels": "cook, history, castle, library, button, museum",
        "title": "Image made by ELG21 on pixabay.com",
        "alt": "Boulder Island",
        "id": 10
    },
        {
        "name": "Cliff Allure",
        "temperature": 18,
        "vegetation": "bushes and trees",
        "inhabitants": 32000,
        "animals": "birds and fish",
        "description": "200 years ago Montgomery Lucas Dabbler won a bet with his friends. He turned the depressing cliffs one couldn't avoid passing, into a modern busy city. It's as if the cliffs are designed to compliment the buildings instead of the other way around. Going to a concert or art exhibition here is quite an experience.",
        "img": "./Images/town-1797892_640.jpg",
        "labels": "cliff, party, swimming, concert, music, art exhibition, river, walking, museum",
        "title": "Image made by mores345 on pixabay.com",
        "alt": "Cliff Allure",
        "id": 11
    }
 ]
};